### ISSUE TITLE
Create and build help command in index.js

### ISSUE THREAD

**Issue by asteed21** [wildlifehexagon/bears-team-27#4]
Need to configure on Express server, to be populated later with actual content.

**Comment by asteed21** [comment]
Some details per the slack documentation:

[https://api.slack.com/slash-commands](url)

**Comment by asteed21** [comment]
Looks like /help is a reserved word, so will shift nomenclature for now.

**Comment by asteed21** [comment]
Some general info on slack slash commands:

[https://api.slack.com/tutorials/slash-commands-style-guide](url)

**Comment by erichartline** [comment]
Good catch on /help. It looks like we need to set up a general command for our bot so we can then add in stuff like `help`, `daily`, etc.

I guess that could tie in to a new name for our bot (currently Interview Bot). I set up the default command as `interview` but that can easily be changed.

Anyone have ideas on a new bot name and/or default command?

**Comment by ermarie** [comment]
Here's a little bit on the drop down menus I was telling y'all about:
https://api.slack.com/docs/message-menus

**Comment by ermarie** [comment]
Buttons are also an option:
https://api.slack.com/docs/message-buttons
Though the drop down seems to be the preferred method from what I've read

**Comment by erichartline** [comment]
`/tiger-help` command with interactive messaging has been implemented.
